### ISSUE TITLE
Fix typo in legal documentation

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/puris-backend#18]
The CONTRIBUTING.md file has a typo in the filename and is therefore not recognized by the 
[Legal Documentation Generator](https://www.eclipse.org/projects/tools/documentation.php?id=automotive.tractusx) checks.

@mhellmeier could you please fix this?

**Comment by mhellmeier** [comment]
Thanks for pointing out the typo; I will fix it.
